# Generated by Django 4.2.7 on 2023-12-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_remove_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ddfffd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
